//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetList
    {
        public int Id { get; set; }
        public Nullable<int> PerformanceID { get; set; }
        public Nullable<int> SongID { get; set; }
    
        public virtual Performance Performance { get; set; }
        public virtual Song Song { get; set; }
    }
}
