//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Song()
        {
            this.SetLists = new HashSet<SetList>();
        }
    
        public int Id { get; set; }
        public string SongName { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<long> BandID { get; set; }
        public Nullable<int> AlbumNumber { get; set; }
    
        public virtual Band Band { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetList> SetLists { get; set; }
    }
}
